name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  animated_text_kit: ^4.0.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  modal_progress_hud: ^0.1.3




dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  http: ^0.13.4

flutter:
  uses-material-design: true

  assets:
  - images/
